name: dsi_env2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ca-certificates=2025.2.25
  - libcxx=17.0.6
  - libffi=3.3
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=25.1
  - python=3.9.12
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - appnope==0.1.4
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - av==15.0.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - fsspec==2025.5.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.2
      - idna==3.10
      - imageio==2.37.0
      - imbalanced-learn==0.12.4
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras==3.10.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.1.0
      - narwhals==1.46.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.16.0
      - packaging==25.0
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - prompt-toolkit==3.0.51
      - protobuf==4.25.8
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - rpds-py==0.26.0
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.11.4
      - seaborn==0.13.2
      - shap==0.48.0
      - six==1.17.0
      - slicer==0.0.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tokenizers==0.19.1
      - torch==2.2.2
      - torchvision==0.17.2
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.44.2
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xgboost==2.1.4
      - zipp==3.23.0
prefix: /Applications/miniconda3/envs/dsi_env2
